language: java
script: ant build-war
deploy:
   edge: true
   provider: cloudfoundry
   username: natta_nagaraju@yahoo.co.in
   password: nnr999789
   api: https://api.run.pivotal.io
   organization: vz-hackathon-july
   space: development